Repository appscodelabs/gh-release-automation-testing, pull requests merged in 2020-06, with the labels that each got.

#1 pr-1
  .github/workflows/pr_merged.yaml
Labels: tag/v0.1.0

#17 Test pr api
  pr-3.txt
Labels: bug, xyz

#19 Asfsdf sfsd fs
  pr-7.txt
  pr-8.txt
Labels: automerge

#20 sfs sfsdf sfsdf
  pr-9.txt
Labels: automerge
